/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts/$accountId'
import { Route as AccountsAccountIdMandatesRouteImport } from './routes/accounts/$accountId/mandates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsAccountIdMandatesRoute =
  AccountsAccountIdMandatesRouteImport.update({
    id: '/mandates',
    path: '/mandates',
    getParentRoute: () => AccountsAccountIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/': typeof AccountsIndexRoute
  '/accounts/$accountId/mandates': typeof AccountsAccountIdMandatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts': typeof AccountsIndexRoute
  '/accounts/$accountId/mandates': typeof AccountsAccountIdMandatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/accounts/$accountId': typeof AccountsAccountIdRouteWithChildren
  '/accounts/': typeof AccountsIndexRoute
  '/accounts/$accountId/mandates': typeof AccountsAccountIdMandatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/accounts/$accountId'
    | '/accounts/'
    | '/accounts/$accountId/mandates'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/accounts/$accountId' | '/accounts' | '/accounts/$accountId/mandates'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/accounts/$accountId'
    | '/accounts/'
    | '/accounts/$accountId/mandates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/$accountId/mandates': {
      id: '/accounts/$accountId/mandates'
      path: '/mandates'
      fullPath: '/accounts/$accountId/mandates'
      preLoaderRoute: typeof AccountsAccountIdMandatesRouteImport
      parentRoute: typeof AccountsAccountIdRoute
    }
  }
}

interface AccountsAccountIdRouteChildren {
  AccountsAccountIdMandatesRoute: typeof AccountsAccountIdMandatesRoute
}

const AccountsAccountIdRouteChildren: AccountsAccountIdRouteChildren = {
  AccountsAccountIdMandatesRoute: AccountsAccountIdMandatesRoute,
}

const AccountsAccountIdRouteWithChildren =
  AccountsAccountIdRoute._addFileChildren(AccountsAccountIdRouteChildren)

interface AccountsRouteChildren {
  AccountsAccountIdRoute: typeof AccountsAccountIdRouteWithChildren
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsAccountIdRoute: AccountsAccountIdRouteWithChildren,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
